services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: bygaurav-portfolio

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl:ro

    restart: unless-stopped