services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: bygaurav-portfolio

    restart: unless-stopped

    ports:
      - "8080:80"

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro